package me.bdaniels.favmoviequotes;

import android.support.v4.view.MenuItemCompat;
import android.support.v7.app.ActionBarActivity;
import android.os.Bundle;
import android.text.Html;
import android.text.method.LinkMovementMethod;
import android.view.Menu;
import android.view.MenuInflater;
import android.view.MenuItem;
import android.view.View;
import android.widget.RelativeLayout;
import android.widget.SearchView;
import android.widget.TextView;

import java.util.ArrayList;


public class Quotebook extends ActionBarActivity {
    int count = 0;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_quotebook);

        RelativeLayout touch = (RelativeLayout) findViewById(R.id.touch);
        final TextView quoteText = (TextView) findViewById(R.id.quote);
        final TextView personText = (TextView) findViewById(R.id.person);
        final ArrayList<Quote> quoteList = new ArrayList<Quote>();
        Quote quote1 = new Quote("Frankly, my dear, I don't give a damn.","Rhett Butler - Gone with the Wind - 1939");
        quoteList.add(quote1);
        Quote quote2 = new Quote("I'm gonna make him an offer he can't refuse.","Vito Corleone - The Godfather - 1972");
        quoteList.add(quote2);
        Quote quote3 = new Quote("You don't understand! I coulda had class. I coulda been a contender. I could've been somebody, instead of a bum, which is what I am.","Terry Malloy - On the Waterfront - 1954");
        quoteList.add(quote3);
        Quote quote4 = new Quote("Toto, I've a feeling we're not in Kansas anymore.","Dorothy Gale - The Wizard of Oz - 1939");
        quoteList.add(quote4);
        Quote quote5 = new Quote("Here's looking at you, kid.","Rick Blaine - Casablanca - 1942");
        quoteList.add(quote5);
        Quote quote6 = new Quote("Go ahead, make my day.","Harry Callahan - Sudden Impact - 1983");
        quoteList.add(quote6);
        Quote quote7 = new Quote("All right, Mr. DeMille, I'm ready for my close - up.","Norma Desmond - Sunset Boulevard - 1950");
        quoteList.add(quote7);
        Quote quote8 = new Quote("May the Force be with you.","Han Solo - Star Wars - 1977");
        quoteList.add(quote8);
        Quote quote9 = new Quote("Fasten your seatbelts. It's going to be a bumpy night.","Margo Channing - All About Eve - 1950");
        quoteList.add(quote9);
        Quote quote10 = new Quote("You talkin' to me?","Travis Bickle - Taxi Driver - 1976");
        quoteList.add(quote10);
        Quote quote11 = new Quote("What we've got here is failure to communicate.","Captain - Cool Hand Luke - 1967");
        quoteList.add(quote11);
        Quote quote12 = new Quote("I love the smell of napalm in the morning.","Lt. Col. Bill Kilgore - Apocalypse Now - 1979");
        quoteList.add(quote12);
        Quote quote13 = new Quote("Love means never having to say you're sorry.","Jennifer Cavilleri Barrett - Love Story - 1970");
        quoteList.add(quote13);
        Quote quote14 = new Quote("The stuff that dreams are made of.","Sam Spade - The Maltese Falcon - 1941");
        quoteList.add(quote14);
        Quote quote15 = new Quote("E.T. phone home.","E.T. - E.T. the Extra - Terrestrial - 1982");
        quoteList.add(quote15);
        Quote quote16 = new Quote("They call me Mister Tibbs!","Virgil Tibbs - In the Heat of the Night - 1967");
        quoteList.add(quote16);
        Quote quote17 = new Quote("Rosebud.","Charles Foster Kane - Citizen Kane - 1941");
        quoteList.add(quote17);
        Quote quote18 = new Quote("Made it, Ma! Top of the world!","Arthur Cody Jarrett - White Heat - 1949");
        quoteList.add(quote18);
        Quote quote19 = new Quote("I'm as mad as hell, and I'm not going to take this anymore!","Howard Beale - Network - 1976");
        quoteList.add(quote19);
        Quote quote20 = new Quote("Louis, I think this is the beginning of a beautiful friendship.","Rick Blaine - Casablanca - 1942");
        quoteList.add(quote20);
        Quote quote21 = new Quote("A census taker once tried to test me. I ate his liver with some fava beans and a nice Chianti.","Hannibal Lecter - The Silence of the Lambs - 1991");
        quoteList.add(quote21);
        Quote quote22 = new Quote("Bond. James Bond.","James Bond - Dr. No - 1962");
        quoteList.add(quote22);
        Quote quote23 = new Quote("There's no place like home.","Dorothy Gale - The Wizard of Oz - 1939");
        quoteList.add(quote23);
        Quote quote24 = new Quote("I am big! It's the pictures that got small.","Norma Desmond - Sunset Boulevard - 1950");
        quoteList.add(quote24);
        Quote quote25 = new Quote("Show me the money!","Rod Tidwell - Jerry Maguire - 1996");
        quoteList.add(quote25);
        Quote quote26 = new Quote("Why don't you come up sometime and see me?","Lady Lou - She Done Him Wrong - 1933");
        quoteList.add(quote26);
        Quote quote27 = new Quote("I'm walking here! I'm walking here!","Ratso Rizzo - Midnight Cowboy - 1969");
        quoteList.add(quote27);
        Quote quote28 = new Quote("Play it, Sam. Play 'As Time Goes By.'","Ilsa Lund - Casablanca - 1942");
        quoteList.add(quote28);
        Quote quote29 = new Quote("You can't handle the truth!","Col. Nathan R. Jessup - A Few Good Men - 1992");
        quoteList.add(quote29);
        Quote quote30 = new Quote("I want to be alone.","Grusinskaya - Grand Hotel - 1932");
        quoteList.add(quote30);
        Quote quote31 = new Quote("After all, tomorrow is another day!","Scarlett O'Hara - Gone with the Wind - 1939");
        quoteList.add(quote31);
        Quote quote32 = new Quote("Round up the usual suspects.","Capt. Louis Renault - Casablanca - 1942");
        quoteList.add(quote32);
        Quote quote33 = new Quote("I'll have what she's having.","Customer - When Harry Met Sally... - 1989");
        quoteList.add(quote33);
        Quote quote34 = new Quote("You know how to whistle, don't you, Steve? You just put your lips together and blow.","Marie Slim Browning - To Have and Have Not - 1944");
        quoteList.add(quote34);
        Quote quote35 = new Quote("You're gonna need a bigger boat.","Martin Brody - Jaws - 1975");
        quoteList.add(quote35);
        Quote quote36 = new Quote("Badges? We ain't got no badges! We don't need no badges! I don't have to show you any stinking badges!","Gold Hat - The Treasure of the Sierra Madre - 1948");
        quoteList.add(quote36);
        Quote quote37 = new Quote("I'll be back.","The Terminator - The Terminator - 1984");
        quoteList.add(quote37);
        Quote quote38 = new Quote("Today, I consider myself the luckiest man on the face of the Earth.","Lou Gehrig - The Pride of the Yankees - 1942");
        quoteList.add(quote38);
        Quote quote39 = new Quote("If you build it, he will come.","Shoeless Joe Jackson - Field of Dreams - 1989");
        quoteList.add(quote39);
        Quote quote40 = new Quote("My momma always said life was like a box of chocolates. You never know what you're gonna get.","Forrest Gump - Forrest Gump - 1994");
        quoteList.add(quote40);
        Quote quote41 = new Quote("We rob banks.","Clyde Barrow - Bonnie and Clyde - 1967");
        quoteList.add(quote41);
        Quote quote42 = new Quote("Plastics.","Mr. Maguire - The Graduate - 1967");
        quoteList.add(quote42);
        Quote quote43 = new Quote("We'll always have Paris.","Rick Blaine - Casablanca - 1942");
        quoteList.add(quote43);
        Quote quote44 = new Quote("I see dead people.","Cole Sear - The Sixth Sense - 1999");
        quoteList.add(quote44);
        Quote quote45 = new Quote("Stella! Hey, Stella!","Stanley Kowalski - A Streetcar Named Desire - 1951");
        quoteList.add(quote45);
        Quote quote46 = new Quote("Oh, Jerry, don't let's ask for the moon. We have the stars.","Charlotte Vale - Now, Voyager - 1942");
        quoteList.add(quote46);
        Quote quote47 = new Quote("Shane. Shane. Come back!","Joey Starrett - Shane - 1953");
        quoteList.add(quote47);
        Quote quote48 = new Quote("Well, nobody's perfect.","Osgood Fielding III - Some Like It Hot - 1959");
        quoteList.add(quote48);
        Quote quote49 = new Quote("It's alive! It's alive!","Henry Frankenstein - Frankenstein - 1931");
        quoteList.add(quote49);
        Quote quote50 = new Quote("Houston, we have a problem.","Jim Lovell - Apollo 13 - 1995");
        quoteList.add(quote50);
        Quote quote51 = new Quote("You've got to ask yourself one question: 'Do I feel lucky?' Well, do ya, punk?","Harry Callahan - Dirty Harry - 1971");
        quoteList.add(quote51);
        Quote quote52 = new Quote("You had me at 'hello.'","Dorothy Boyd - Jerry Maguire - 1996");
        quoteList.add(quote52);
        Quote quote53 = new Quote("One morning I shot an elephant in my pajamas. How he got in my pajamas, I don't know.","Capt. Geoffrey T. Spaulding - Animal Crackers - 1930");
        quoteList.add(quote53);
        Quote quote54 = new Quote("There's no crying in baseball!","Jimmy Dugan - A League of Their Own - 1992");
        quoteList.add(quote54);
        Quote quote55 = new Quote("La - dee - da, la - dee - da.","Annie Hall - Annie Hall - 1977");
        quoteList.add(quote55);
        Quote quote56 = new Quote("A boy's best friend is his mother.","Norman Bates - Psycho - 1960");
        quoteList.add(quote56);
        Quote quote57 = new Quote("Greed, for lack of a better word, is good.","Gordon Gekko - Wall Street - 1987");
        quoteList.add(quote57);
        Quote quote58 = new Quote("Keep your friends close, but your enemies closer.","Michael Corleone - The Godfather Part II - 1974");
        quoteList.add(quote58);
        Quote quote59 = new Quote("As God is my witness, I'll never be hungry again.","Scarlett O'Hara - Gone with the Wind - 1939");
        quoteList.add(quote59);
        Quote quote60 = new Quote("Well, here's another nice mess you've gotten me into!","Oliver - Sons of the Desert - 1933");
        quoteList.add(quote60);
        Quote quote61 = new Quote("Say 'hello' to my little friend!","Tony Montana - Scarface - 1983");
        quoteList.add(quote61);
        Quote quote62 = new Quote("What a dump.","Rosa Moline - Beyond the Forest - 1949");
        quoteList.add(quote62);
        Quote quote63 = new Quote("Mrs. Robinson, you're trying to seduce me. Aren't you?","Benjamin Braddock - The Graduate - 1967");
        quoteList.add(quote63);
        Quote quote64 = new Quote("Gentlemen, you can't fight in here! This is the War Room!","President Merkin Muffley - Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb - 1964");
        quoteList.add(quote64);
        Quote quote65 = new Quote("Elementary, my dear Watson.","Sherlock Holmes - The Adventures of Sherlock Holmes - 1939");
        quoteList.add(quote65);
        Quote quote66 = new Quote("Take your stinking paws off me, you damned dirty ape.","George Taylor - Planet of the Apes - 1968");
        quoteList.add(quote66);
        Quote quote67 = new Quote("Of all the gin joints in all the towns in all the world, she walks into mine.","Rick Blaine - Casablanca - 1942");
        quoteList.add(quote67);
        Quote quote68 = new Quote("Here's Johnny!","Jack Torrance - The Shining - 1980");
        quoteList.add(quote68);
        Quote quote69 = new Quote("They're here!","Carol Anne Freeling - Poltergeist - 1982");
        quoteList.add(quote69);
        Quote quote70 = new Quote("Is it safe?","Dr. Christian Szell - Marathon Man - 1976");
        quoteList.add(quote70);
        Quote quote71 = new Quote("Wait a minute, wait a minute. You ain't heard nothin' yet!","Jakie Rabinowitz/Jack Robin - The Jazz Singer - 1927");
        quoteList.add(quote71);
        Quote quote72 = new Quote("No wire hangers, ever!","Joan Crawford - Mommie Dearest - 1981");
        quoteList.add(quote72);
        Quote quote73 = new Quote("Mother of mercy, is this the end of Rico?","Cesare Enrico Rico Bandello - Little Caesar - 1930");
        quoteList.add(quote73);
        Quote quote74 = new Quote("Forget it, Jake, it's Chinatown.","Lawrence Walsh - Chinatown - 1974");
        quoteList.add(quote74);
        Quote quote75 = new Quote("I have always depended on the kindness of strangers.","Blanche DuBois - A Streetcar Named Desire - 1951");
        quoteList.add(quote75);
        Quote quote76 = new Quote("Hasta la vista, baby.","The Terminator - Terminator 2: Judgment Day - 1991");
        quoteList.add(quote76);
        Quote quote77 = new Quote("Soylent Green is people!","Det. Robert Thorn - Soylent Green - 1973");
        quoteList.add(quote77);
        Quote quote78 = new Quote("Open the pod bay doors, HAL.","Dave Bowman - 2001: A Space Odyssey - 1968");
        quoteList.add(quote78);
        Quote quote79 = new Quote("Striker: Surely you cant be serious. Rumack: I am serious...and don't call me Shirley.","Ted Striker and Dr. Rumack - Airplane! - 1980");
        quoteList.add(quote79);
        Quote quote80 = new Quote("Yo, Adrian!","Rocky Balboa - Rocky - 1976");
        quoteList.add(quote80);
        Quote quote81 = new Quote("Hello, gorgeous.","Fanny Brice - Funny Girl - 1968");
        quoteList.add(quote81);
        Quote quote82 = new Quote("Toga! Toga!","John Bluto Blutarsky - National Lampoon's Animal House - 1978");
        quoteList.add(quote82);
        Quote quote83 = new Quote("Listen to them. Children of the night. What music they make.","Count Dracula - Dracula - 1931");
        quoteList.add(quote83);
        Quote quote84 = new Quote("Oh, no, it wasn't the airplanes. It was Beauty killed the Beast.","Carl Denham - King Kong - 1933");
        quoteList.add(quote84);
        Quote quote85 = new Quote("My precious.","Gollum - The Lord of the Rings: The Two Towers - 2002");
        quoteList.add(quote85);
        Quote quote86 = new Quote("Attica! Attica!","Sonny Wortzik - Dog Day Afternoon - 1975");
        quoteList.add(quote86);
        Quote quote87 = new Quote("Sawyer, you're going out a youngster, but you've got to come back a star!","Julian Marsh - 42nd Street - 1933");
        quoteList.add(quote87);
        Quote quote88 = new Quote("Listen to me, mister. You're my knight in shining armor. Don't you forget it. You're going to get back on that horse, and I'm going to be right behind you, holding on tight, and away we're gonna go, go, go!","Ethel Thayer - On Golden Pond - 1981");
        quoteList.add(quote88);
        Quote quote89 = new Quote("Tell 'em to go out there with all they got and win just one for the Gipper.","Knute Rockne - Knute Rockne, All American - 1940");
        quoteList.add(quote89);
        Quote quote90 = new Quote("A martini. Shaken, not stirred.","James Bond - Goldfinger - 1964");
        quoteList.add(quote90);
        Quote quote91 = new Quote("Who's on first?","Dexter - The Naughty Nineties - 1945");
        quoteList.add(quote91);
        Quote quote92 = new Quote("Cinderella story. Outta nowhere. A former greenskeeper, now, about to become the Masters champion. It looks like a mirac...It's in the hole! It's in the hole! It's in the hole!","Carl Spackler - Caddyshack - 1980");
        quoteList.add(quote92);
        Quote quote93 = new Quote("Life is a banquet, and most poor suckers are starving to death!","Mame Dennis - Auntie Mame - 1958");
        quoteList.add(quote93);
        Quote quote94 = new Quote("I feel the need - the need for speed!","Lt. Pete Maverick Mitchell and Lt. Nick Goose Bradshaw - Top Gun - 1986");
        quoteList.add(quote94);
        Quote quote95 = new Quote("Carpe diem. Seize the day, boys. Make your lives extraordinary.","John Keating - Dead Poets Society - 1989");
        quoteList.add(quote95);
        Quote quote96 = new Quote("Snap out of it!","Loretta Castorini - Moonstruck - 1987");
        quoteList.add(quote96);
        Quote quote97 = new Quote("My mother thanks you. My father thanks you. My sister thanks you. And I thank you.","George M. Cohan - Yankee Doodle Dandy - 1942");
        quoteList.add(quote97);
        Quote quote98 = new Quote("Nobody puts Baby in the corner.","Johnny Castle - Dirty Dancing - 1987");
        quoteList.add(quote98);
        Quote quote99 = new Quote("I'll get you, my pretty, and your little dog too!","Wicked Witch of the West - The Wizard of Oz - 1939");
        quoteList.add(quote99);
        Quote quote100 = new Quote("I'm the king of the world!","Jack Dawson - Titanic - 1997");
        quoteList.add(quote100);

        touch.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                if (count < quoteList.size()) {
                    Quote q = quoteList.get(count);
                    quoteText.setText(q.getQuote());
                    personText.setText(q.getPerson());
                    count = count + 1;
                } else{
                    count = 0;
                }
            }
        });
    }


}
